// Generated by scripts/build-assets.mjs. Do not edit.
import type { ImageSourcePropType } from 'react-native';

export type AvatarGroup = 'female' | 'male' | 'unknown';
export const AVATAR_GROUPS: Record<AvatarGroup, string[]> = {
  'female': [
    'Amara',
    'Camila',
    'Elena',
    'Freya',
    'Isabella',
    'Ngozi',
    'Priya',
    'Sophia',
    'Yuki',
    'Zara'
  ],
  'male': [
    'Anton',
    'Diego',
    'Erik',
    'Hiroshi',
    'Jamal',
    'Kai',
    'Liam',
    'Marcus',
    'Rashid',
    'Tobias'
  ],
  'unknown': [
    'Bunny',
    'Crocodile',
    'Jester',
    'Robot',
    'Shark'
  ]
};
/** key = '<group>/<Name>', the same value user_settings.custom_avatar_image used in the PWA. */
export const AVATAR_IMAGES: Record<string, ImageSourcePropType> = {
  'female/Amara': require('@/assets/avatars/female/Amara.webp'),
  'female/Camila': require('@/assets/avatars/female/Camila.webp'),
  'female/Elena': require('@/assets/avatars/female/Elena.webp'),
  'female/Freya': require('@/assets/avatars/female/Freya.webp'),
  'female/Isabella': require('@/assets/avatars/female/Isabella.webp'),
  'female/Ngozi': require('@/assets/avatars/female/Ngozi.webp'),
  'female/Priya': require('@/assets/avatars/female/Priya.webp'),
  'female/Sophia': require('@/assets/avatars/female/Sophia.webp'),
  'female/Yuki': require('@/assets/avatars/female/Yuki.webp'),
  'female/Zara': require('@/assets/avatars/female/Zara.webp'),
  'male/Anton': require('@/assets/avatars/male/Anton.webp'),
  'male/Diego': require('@/assets/avatars/male/Diego.webp'),
  'male/Erik': require('@/assets/avatars/male/Erik.webp'),
  'male/Hiroshi': require('@/assets/avatars/male/Hiroshi.webp'),
  'male/Jamal': require('@/assets/avatars/male/Jamal.webp'),
  'male/Kai': require('@/assets/avatars/male/Kai.webp'),
  'male/Liam': require('@/assets/avatars/male/Liam.webp'),
  'male/Marcus': require('@/assets/avatars/male/Marcus.webp'),
  'male/Rashid': require('@/assets/avatars/male/Rashid.webp'),
  'male/Tobias': require('@/assets/avatars/male/Tobias.webp'),
  'unknown/Bunny': require('@/assets/avatars/unknown/Bunny.webp'),
  'unknown/Crocodile': require('@/assets/avatars/unknown/Crocodile.webp'),
  'unknown/Jester': require('@/assets/avatars/unknown/Jester.webp'),
  'unknown/Robot': require('@/assets/avatars/unknown/Robot.webp'),
  'unknown/Shark': require('@/assets/avatars/unknown/Shark.webp'),
};
