// Generated by scripts/build-assets.mjs. Do not edit.
import type { ImageSourcePropType } from 'react-native';

/** Category renders (images/app-ui-images/category-<name>.png), 256 px webp with alpha; a category without a render is absent. */
export const CATEGORY_IMAGES: Record<string, ImageSourcePropType> = {
  vegetable: require('@/assets/categories/vegetable.webp'),
  fruit: require('@/assets/categories/fruit.webp'),
  nut_seed: require('@/assets/categories/nut_seed.webp'),
  legume: require('@/assets/categories/legume.webp'),
  whole_grain: require('@/assets/categories/whole_grain.webp'),
  ferment: require('@/assets/categories/ferment.webp'),
};
