// Generated by scripts/build-assets.mjs. Do not edit.
import type { ImageSourcePropType } from 'react-native';

export type CupLevel = 'bronze' | 'silver' | 'gold';
/** Card-level cups (images/app-ui-images/<Level>_Cup.png), 256 px webp with alpha. */
export const CUP_IMAGES: Record<CupLevel, ImageSourcePropType> = {
  bronze: require('@/assets/cups/bronze.webp'),
  silver: require('@/assets/cups/silver.webp'),
  gold: require('@/assets/cups/gold.webp'),
};
