// Generated by scripts/build-assets.mjs. Do not edit.
import type { ImageSourcePropType } from 'react-native';

/** Gold renders (bucket food-images/gold/<file>), 256 px webp; a plant without one keeps its normal render. */
export const PLANT_GOLD_IMAGES: Record<string, ImageSourcePropType> = {

};
