// Generated by scripts/build-assets.mjs. Do not edit.
import type { ImageSourcePropType } from 'react-native';

/** Prize renders by stamp image id (bucket achievements/achievement-<id>.png), 256 px webp with alpha. */
export const STAMP_IMAGES: Record<string, ImageSourcePropType> = {
  explorer: require('@/assets/stamps/explorer.webp'),
  green_machine: require('@/assets/stamps/green_machine.webp'),
  fruit_basket: require('@/assets/stamps/fruit_basket.webp'),
  herb_garden: require('@/assets/stamps/herb_garden.webp'),
  nutcracker: require('@/assets/stamps/nutcracker.webp'),
  bean_counter: require('@/assets/stamps/bean_counter.webp'),
  grain_train: require('@/assets/stamps/grain_train.webp'),
  bubbly: require('@/assets/stamps/bubbly.webp'),
  superfood: require('@/assets/stamps/superfood.webp'),
  tomato_family: require('@/assets/stamps/tomato_family.webp'),
  rainbow: require('@/assets/stamps/rainbow.webp'),
  big_dinner: require('@/assets/stamps/big_dinner.webp'),
  regular_table: require('@/assets/stamps/regular_table.webp'),
  steady_weeks: require('@/assets/stamps/steady_weeks.webp'),
  table_talk: require('@/assets/stamps/table_talk.webp'),
  family_of_thirty: require('@/assets/stamps/family_of_thirty.webp'),
  regulars: require('@/assets/stamps/regulars.webp'),
  full_table: require('@/assets/stamps/full_table.webp'),
  curious: require('@/assets/stamps/curious.webp'),
};
