// Generated by scripts/build-assets.mjs. Do not edit.
import type { ImageSourcePropType } from 'react-native';

export type StatKey = 'streak' | 'longestStreak' | 'weeksAtGoal' | 'bestWeek';
/** The stats screen's record tiles (images/app-ui-images/<name>.png), 256 px webp with alpha. */
export const STAT_IMAGES: Partial<Record<StatKey, ImageSourcePropType>> = {
  streak: require('@/assets/stats/streak.webp'),
  longestStreak: require('@/assets/stats/longestStreak.webp'),
  weeksAtGoal: require('@/assets/stats/weeksAtGoal.webp'),
  bestWeek: require('@/assets/stats/bestWeek.webp'),
};
