// Generated by the Supabase MCP `generate_typescript_types` on 2026-09-16 after migrations 0001–0006.
// Regenerate after every migration; do not edit by hand.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      achievement_unlocks: {
        Row: {
          level: number
          achievement_id: string
          household_id: string
          id: string
          member_id: string | null
          seen_at: string | null
          unlocked_at: string
        }
        Insert: {
          level?: number
          achievement_id: string
          household_id: string
          id?: string
          member_id?: string | null
          seen_at?: string | null
          unlocked_at?: string
        }
        Update: {
          level?: number
          achievement_id?: string
          household_id?: string
          id?: string
          member_id?: string | null
          seen_at?: string | null
          unlocked_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "achievement_unlocks_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "achievement_unlocks_member_id_fkey"
            columns: ["member_id"]
            isOneToOne: false
            referencedRelation: "household_members"
            referencedColumns: ["id"]
          },
        ]
      }
      app_events: {
        Row: {
          client_ts: string | null
          created_at: string
          household_id: string | null
          id: number
          name: string
          props: Json
          user_id: string
        }
        Insert: {
          client_ts?: string | null
          created_at?: string
          household_id?: string | null
          id?: never
          name: string
          props?: Json
          user_id?: string
        }
        Update: {
          client_ts?: string | null
          created_at?: string
          household_id?: string | null
          id?: never
          name?: string
          props?: Json
          user_id?: string
        }
        Relationships: []
      }
      friendships: {
        Row: {
          addressee: string
          created_at: string | null
          id: string
          requester: string
          status: string
        }
        Insert: {
          addressee: string
          created_at?: string | null
          id?: string
          requester: string
          status: string
        }
        Update: {
          addressee?: string
          created_at?: string | null
          id?: string
          requester?: string
          status?: string
        }
        Relationships: []
      }
      household_members: {
        Row: {
          archived_at: string | null
          avatar_bg: string | null
          avatar_image: string | null
          color_index: number
          created_at: string
          household_id: string
          id: string
          kind: string
          name: string
          sort_order: number
          user_id: string | null
        }
        Insert: {
          archived_at?: string | null
          avatar_bg?: string | null
          avatar_image?: string | null
          color_index?: number
          created_at?: string
          household_id: string
          id?: string
          kind: string
          name: string
          sort_order?: number
          user_id?: string | null
        }
        Update: {
          archived_at?: string | null
          avatar_bg?: string | null
          avatar_image?: string | null
          color_index?: number
          created_at?: string
          household_id?: string
          id?: string
          kind?: string
          name?: string
          sort_order?: number
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "household_members_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
        ]
      }
      household_users: {
        Row: {
          household_id: string
          joined_at: string
          role: string
          user_id: string
        }
        Insert: {
          household_id: string
          joined_at?: string
          role?: string
          user_id: string
        }
        Update: {
          household_id?: string
          joined_at?: string
          role?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "household_users_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
        ]
      }
      households: {
        Row: {
          created_at: string
          created_by: string
          dinner_time: string
          id: string
          name: string
          onboarded_at: string | null
          plan: string
          timezone: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by: string
          dinner_time?: string
          id?: string
          name?: string
          onboarded_at?: string | null
          plan?: string
          timezone?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string
          dinner_time?: string
          id?: string
          name?: string
          onboarded_at?: string | null
          plan?: string
          timezone?: string
          updated_at?: string
        }
        Relationships: []
      }
      learn_article_content: {
        Row: {
          article_id: string
          body_md: string
          created_at: string
          locale: string
          meta_description: string | null
          meta_title: string | null
          reading_time_min: number | null
          related_article_slugs: string[]
          sd_citations: Json | null
          sd_faq: Json | null
          sd_keywords: string[]
          subtitle: string | null
          title: string
          updated_at: string
        }
        Insert: {
          article_id: string
          body_md?: string
          created_at?: string
          locale: string
          meta_description?: string | null
          meta_title?: string | null
          reading_time_min?: number | null
          related_article_slugs?: string[]
          sd_citations?: Json | null
          sd_faq?: Json | null
          sd_keywords?: string[]
          subtitle?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          article_id?: string
          body_md?: string
          created_at?: string
          locale?: string
          meta_description?: string | null
          meta_title?: string | null
          reading_time_min?: number | null
          related_article_slugs?: string[]
          sd_citations?: Json | null
          sd_faq?: Json | null
          sd_keywords?: string[]
          subtitle?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "learn_article_content_article_id_fkey"
            columns: ["article_id"]
            isOneToOne: false
            referencedRelation: "learn_articles"
            referencedColumns: ["id"]
          },
        ]
      }
      learn_articles: {
        Row: {
          cover_image_url: string | null
          created_at: string
          display_order: number
          emoji: string | null
          id: string
          is_published: boolean
          pillar_id: string | null
          published_at: string | null
          slug: string
          type: Database["public"]["Enums"]["article_type"]
          updated_at: string
        }
        Insert: {
          cover_image_url?: string | null
          created_at?: string
          display_order?: number
          emoji?: string | null
          id?: string
          is_published?: boolean
          pillar_id?: string | null
          published_at?: string | null
          slug: string
          type: Database["public"]["Enums"]["article_type"]
          updated_at?: string
        }
        Update: {
          cover_image_url?: string | null
          created_at?: string
          display_order?: number
          emoji?: string | null
          id?: string
          is_published?: boolean
          pillar_id?: string | null
          published_at?: string | null
          slug?: string
          type?: Database["public"]["Enums"]["article_type"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "learn_articles_pillar_id_fkey"
            columns: ["pillar_id"]
            isOneToOne: false
            referencedRelation: "learn_articles"
            referencedColumns: ["id"]
          },
        ]
      }
      notification_log: {
        Row: {
          clicked_at: string | null
          delivered: boolean | null
          delivered_at: string | null
          household_id: string | null
          id: string
          logged_within_3h: boolean | null
          opened_at: string | null
          push_token_id: string | null
          sent_at: string
          ticket_id: string | null
          type: string
          user_id: string
        }
        Insert: {
          clicked_at?: string | null
          delivered?: boolean | null
          delivered_at?: string | null
          household_id?: string | null
          id?: string
          logged_within_3h?: boolean | null
          opened_at?: string | null
          push_token_id?: string | null
          sent_at?: string
          ticket_id?: string | null
          type: string
          user_id: string
        }
        Update: {
          clicked_at?: string | null
          delivered?: boolean | null
          delivered_at?: string | null
          household_id?: string | null
          id?: string
          logged_within_3h?: boolean | null
          opened_at?: string | null
          push_token_id?: string | null
          sent_at?: string
          ticket_id?: string | null
          type?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notification_log_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notification_log_push_token_id_fkey"
            columns: ["push_token_id"]
            isOneToOne: false
            referencedRelation: "push_tokens"
            referencedColumns: ["id"]
          },
        ]
      }
      plant_facts: {
        Row: {
          generated_at: string
          kid_fact: string
          locale: string
          model: string | null
          parent_tip: string
          plant_id: string
          reviewed_at: string | null
          status: string
        }
        Insert: {
          generated_at?: string
          kid_fact: string
          locale: string
          model?: string | null
          parent_tip: string
          plant_id: string
          reviewed_at?: string | null
          status?: string
        }
        Update: {
          generated_at?: string
          kid_fact?: string
          locale?: string
          model?: string | null
          parent_tip?: string
          plant_id?: string
          reviewed_at?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "plant_facts_plant_id_fkey"
            columns: ["plant_id"]
            isOneToOne: false
            referencedRelation: "plants"
            referencedColumns: ["id"]
          },
        ]
      }
      plant_logs: {
        Row: {
          household_id: string
          id: string
          logged_at: string
          logged_on: string
          member_id: string
          plant_id: string
          user_id: string
        }
        Insert: {
          household_id: string
          id?: string
          logged_at?: string
          logged_on: string
          member_id: string
          plant_id: string
          user_id: string
        }
        Update: {
          household_id?: string
          id?: string
          logged_at?: string
          logged_on?: string
          member_id?: string
          plant_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "plant_logs_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "plant_logs_member_id_fkey"
            columns: ["member_id"]
            isOneToOne: false
            referencedRelation: "household_members"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "plant_logs_plant_id_fkey"
            columns: ["plant_id"]
            isOneToOne: false
            referencedRelation: "plants"
            referencedColumns: ["id"]
          },
        ]
      }
      plant_submissions: {
        Row: {
          created_at: string
          id: string
          linked_plant_id: string | null
          notes: string | null
          proposed_category:
            | Database["public"]["Enums"]["plant_category"]
            | null
          proposed_name: string
          reviewed_at: string | null
          reviewed_by: string | null
          status: Database["public"]["Enums"]["submission_status"]
          submitted_by: string
        }
        Insert: {
          created_at?: string
          id?: string
          linked_plant_id?: string | null
          notes?: string | null
          proposed_category?:
            | Database["public"]["Enums"]["plant_category"]
            | null
          proposed_name: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: Database["public"]["Enums"]["submission_status"]
          submitted_by: string
        }
        Update: {
          created_at?: string
          id?: string
          linked_plant_id?: string | null
          notes?: string | null
          proposed_category?:
            | Database["public"]["Enums"]["plant_category"]
            | null
          proposed_name?: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: Database["public"]["Enums"]["submission_status"]
          submitted_by?: string
        }
        Relationships: [
          {
            foreignKeyName: "plant_submissions_linked_plant_id_fkey"
            columns: ["linked_plant_id"]
            isOneToOne: false
            referencedRelation: "plants"
            referencedColumns: ["id"]
          },
        ]
      }
      plant_translations: {
        Row: {
          locale: string
          name: string
          plant_id: string
        }
        Insert: {
          locale: string
          name: string
          plant_id: string
        }
        Update: {
          locale?: string
          name?: string
          plant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "plant_translations_plant_id_fkey"
            columns: ["plant_id"]
            isOneToOne: false
            referencedRelation: "plants"
            referencedColumns: ["id"]
          },
        ]
      }
      plants: {
        Row: {
          botanical_family: string | null
          category: Database["public"]["Enums"]["plant_category"]
          color: Database["public"]["Enums"]["plant_color"] | null
          created_at: string
          emoji: string | null
          id: string
          image_url: string | null
          is_active: boolean
          is_seasonal: boolean
          is_superfood: boolean
          name: string
          search_aliases: string[]
          season_months: number[] | null
          slug: string
          subcategory: string | null
        }
        Insert: {
          botanical_family?: string | null
          category: Database["public"]["Enums"]["plant_category"]
          color?: Database["public"]["Enums"]["plant_color"] | null
          created_at?: string
          emoji?: string | null
          id?: string
          image_url?: string | null
          is_active?: boolean
          is_seasonal?: boolean
          is_superfood?: boolean
          name: string
          search_aliases?: string[]
          season_months?: number[] | null
          slug: string
          subcategory?: string | null
        }
        Update: {
          botanical_family?: string | null
          category?: Database["public"]["Enums"]["plant_category"]
          color?: Database["public"]["Enums"]["plant_color"] | null
          created_at?: string
          emoji?: string | null
          id?: string
          image_url?: string | null
          is_active?: boolean
          is_seasonal?: boolean
          is_superfood?: boolean
          name?: string
          search_aliases?: string[]
          season_months?: number[] | null
          slug?: string
          subcategory?: string | null
        }
        Relationships: []
      }
      push_subscriptions: {
        Row: {
          auth: string
          created_at: string
          endpoint: string
          failure_count: number
          id: string
          last_failure_at: string | null
          last_success_at: string | null
          p256dh: string
          user_agent: string | null
          user_id: string
        }
        Insert: {
          auth: string
          created_at?: string
          endpoint: string
          failure_count?: number
          id?: string
          last_failure_at?: string | null
          last_success_at?: string | null
          p256dh: string
          user_agent?: string | null
          user_id: string
        }
        Update: {
          auth?: string
          created_at?: string
          endpoint?: string
          failure_count?: number
          id?: string
          last_failure_at?: string | null
          last_success_at?: string | null
          p256dh?: string
          user_agent?: string | null
          user_id?: string
        }
        Relationships: []
      }
      push_tokens: {
        Row: {
          app_version: string | null
          created_at: string
          device_name: string | null
          expo_push_token: string
          failure_count: number
          id: string
          last_seen_at: string
          platform: string
          user_id: string
        }
        Insert: {
          app_version?: string | null
          created_at?: string
          device_name?: string | null
          expo_push_token: string
          failure_count?: number
          id?: string
          last_seen_at?: string
          platform: string
          user_id: string
        }
        Update: {
          app_version?: string | null
          created_at?: string
          device_name?: string | null
          expo_push_token?: string
          failure_count?: number
          id?: string
          last_seen_at?: string
          platform?: string
          user_id?: string
        }
        Relationships: []
      }
      recipe_batches: {
        Row: {
          created_at: string | null
          id: string
          recipes: Json
          selected_plants: string[]
          user_id: string
          week_start: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          recipes?: Json
          selected_plants?: string[]
          user_id: string
          week_start: string
        }
        Update: {
          created_at?: string | null
          id?: string
          recipes?: Json
          selected_plants?: string[]
          user_id?: string
          week_start?: string
        }
        Relationships: []
      }
      survey_question_translations: {
        Row: {
          help_text: string | null
          label: string
          locale: string
          options_override: Json | null
          question_id: string
        }
        Insert: {
          help_text?: string | null
          label: string
          locale: string
          options_override?: Json | null
          question_id: string
        }
        Update: {
          help_text?: string | null
          label?: string
          locale?: string
          options_override?: Json | null
          question_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "survey_question_translations_question_id_fkey"
            columns: ["question_id"]
            isOneToOne: false
            referencedRelation: "survey_questions"
            referencedColumns: ["id"]
          },
        ]
      }
      survey_questions: {
        Row: {
          created_at: string
          display_order: number
          id: string
          is_active: boolean
          key: string
          options: Json | null
          section: string
          type: string
        }
        Insert: {
          created_at?: string
          display_order: number
          id?: string
          is_active?: boolean
          key: string
          options?: Json | null
          section: string
          type: string
        }
        Update: {
          created_at?: string
          display_order?: number
          id?: string
          is_active?: boolean
          key?: string
          options?: Json | null
          section?: string
          type?: string
        }
        Relationships: []
      }
      survey_responses: {
        Row: {
          answer: Json | null
          answered_at: string | null
          id: string
          question_id: string
          status: string
          updated_at: string
          user_id: string
        }
        Insert: {
          answer?: Json | null
          answered_at?: string | null
          id?: string
          question_id: string
          status?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          answer?: Json | null
          answered_at?: string | null
          id?: string
          question_id?: string
          status?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "survey_responses_question_id_fkey"
            columns: ["question_id"]
            isOneToOne: false
            referencedRelation: "survey_questions"
            referencedColumns: ["id"]
          },
        ]
      }
      user_settings: {
        Row: {
          active_border: string | null
          avatar_url: string | null
          created_at: string
          custom_avatar_bg: string | null
          custom_avatar_image: string | null
          locale: string
          notif_backoff_until: string | null
          notif_daily_reminder: boolean
          notif_essential: boolean
          notif_marketing: boolean
          notif_reengagement: boolean
          notif_streak_rescue: boolean
          notif_weekly_nudge: boolean
          notifications_enabled: boolean
          push_prompt_at: string | null
          survey_dismissed_at: string | null
          timezone: string
          unlocked_borders: string[] | null
          updated_at: string
          user_id: string
          username: string | null
          week_start_day: number
          weekly_variety_goal: number
        }
        Insert: {
          active_border?: string | null
          avatar_url?: string | null
          created_at?: string
          custom_avatar_bg?: string | null
          custom_avatar_image?: string | null
          locale?: string
          notif_backoff_until?: string | null
          notif_daily_reminder?: boolean
          notif_essential?: boolean
          notif_marketing?: boolean
          notif_reengagement?: boolean
          notif_streak_rescue?: boolean
          notif_weekly_nudge?: boolean
          notifications_enabled?: boolean
          push_prompt_at?: string | null
          survey_dismissed_at?: string | null
          timezone?: string
          unlocked_borders?: string[] | null
          updated_at?: string
          user_id: string
          username?: string | null
          week_start_day?: number
          weekly_variety_goal?: number
        }
        Update: {
          active_border?: string | null
          avatar_url?: string | null
          created_at?: string
          custom_avatar_bg?: string | null
          custom_avatar_image?: string | null
          locale?: string
          notif_backoff_until?: string | null
          notif_daily_reminder?: boolean
          notif_essential?: boolean
          notif_marketing?: boolean
          notif_reengagement?: boolean
          notif_streak_rescue?: boolean
          notif_weekly_nudge?: boolean
          notifications_enabled?: boolean
          push_prompt_at?: string | null
          survey_dismissed_at?: string | null
          timezone?: string
          unlocked_borders?: string[] | null
          updated_at?: string
          user_id?: string
          username?: string | null
          week_start_day?: number
          weekly_variety_goal?: number
        }
        Relationships: []
      }
      weekly_advice: {
        Row: {
          advice: Json
          created_at: string | null
          id: string
          user_id: string
          week_start: string
        }
        Insert: {
          advice: Json
          created_at?: string | null
          id?: string
          user_id: string
          week_start: string
        }
        Update: {
          advice?: Json
          created_at?: string | null
          id?: string
          user_id?: string
          week_start?: string
        }
        Relationships: []
      }
    }
    Views: {
      analytics_churn_rate: {
        Row: {
          churn_rate_pct: number | null
          churned_users: number | null
          previously_active: number | null
          week: string | null
        }
        Relationships: []
      }
      analytics_new_users_per_week: {
        Row: {
          new_users: number | null
          week: string | null
        }
        Relationships: []
      }
      analytics_weekly_active_users: {
        Row: {
          mau_28d: number | null
          wau: number | null
          week: string | null
        }
        Relationships: []
      }
      analytics_weekly_goal_completion: {
        Row: {
          active_users: number | null
          completion_pct: number | null
          goal_completers: number | null
          week: string | null
        }
        Relationships: []
      }
      analytics_weekly_retention: {
        Row: {
          cohort_size: number | null
          cohort_week: string | null
          retained_users: number | null
          retention_pct: number | null
          weeks_since_join: number | null
        }
        Relationships: []
      }
      weekly_user_plant_counts: {
        Row: {
          plant_bucket: string | null
          unique_plants: number | null
          user_id: string | null
          week_start: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      category_breakdown: {
        Args: { p_user_id?: string }
        Returns: {
          category: Database["public"]["Enums"]["plant_category"]
          total_in_category: number
          unique_count: number
        }[]
      }
      current_streak: { Args: { p_user_id?: string }; Returns: number }
      current_week_plants: {
        Args: { p_user_id?: string; p_week_start?: string }
        Returns: {
          botanical_family: string | null
          category: Database["public"]["Enums"]["plant_category"]
          color: Database["public"]["Enums"]["plant_color"] | null
          created_at: string
          emoji: string | null
          id: string
          image_url: string | null
          is_active: boolean
          is_seasonal: boolean
          is_superfood: boolean
          name: string
          search_aliases: string[]
          season_months: number[] | null
          slug: string
          subcategory: string | null
        }[]
        SetofOptions: {
          from: "*"
          to: "plants"
          isOneToOne: false
          isSetofReturn: true
        }
      }
      daily_history: {
        Args: { p_days?: number; p_user_id?: string }
        Returns: {
          date: string
          variety: number
        }[]
      }
      fill_rate: {
        Args: { p_user_id?: string; p_window_days?: number }
        Returns: number
      }
      household_daily_activity: {
        Args: { p_days?: number; p_household_id?: string }
        Returns: {
          day: string
          distinct_plants: number
          member_id: string
        }[]
      }
      household_streak: {
        Args: { p_household_id?: string }
        Returns: {
          at_risk: boolean
          current_streak: number
          freeze_used_on: string
          logged_today: boolean
          longest_streak: number
        }[]
      }
      household_week_plants: {
        Args: { p_household_id?: string; p_week_start?: string }
        Returns: {
          first_on: string
          member_ids: string[]
          plant_id: string
        }[]
      }
      household_weekly_history: {
        Args: { p_household_id?: string; p_weeks?: number }
        Returns: {
          colours: number
          hit_goal: boolean
          variety: number
          week_start: string
        }[]
      }
      household_weekly_variety: {
        Args: { p_household_id?: string; p_week_start?: string }
        Returns: number
      }
      is_household_member: { Args: { hid: string }; Returns: boolean }
      leaderboard: {
        Args: { p_limit?: number }
        Returns: {
          active_border: string
          avatar_bg: string
          avatar_url: string
          is_me: boolean
          rank: number
          unique_plants: number
          username: string
        }[]
      }
      leaderboard_friends: {
        Args: { p_limit?: number }
        Returns: {
          active_border: string
          avatar_bg: string
          avatar_url: string
          is_me: boolean
          rank: number
          unique_plants: number
          user_id: string
          username: string
        }[]
      }
      leaderboard_friends_streaks: {
        Args: { p_limit?: number }
        Returns: {
          active_border: string
          avatar_bg: string
          avatar_url: string
          is_me: boolean
          rank: number
          streak: number
          user_id: string
          username: string
        }[]
      }
      leaderboard_streaks: {
        Args: { p_limit?: number }
        Returns: {
          active_border: string
          avatar_bg: string
          avatar_url: string
          is_me: boolean
          rank: number
          streak: number
          username: string
        }[]
      }
      mark_notification_opened: { Args: { p_id: string }; Returns: undefined }
      member_taste_counts: {
        Args: { p_household_id?: string }
        Returns: {
          first_on: string
          last_on: string
          member_id: string
          plant_id: string
          tastes: number
        }[]
      }
      my_household_id: { Args: never; Returns: string }
      pending_requests: {
        Args: never
        Returns: {
          active_border: string
          avatar_bg: string
          avatar_url: string
          id: string
          other_user_id: string
          type: string
          username: string
        }[]
      }
      search_users: {
        Args: { p_query: string }
        Returns: {
          avatar_bg: string
          avatar_url: string
          total_plants: number
          user_id: string
          username: string
        }[]
      }
      show_limit: { Args: never; Returns: number }
      show_trgm: { Args: { "": string }; Returns: string[] }
      social_friends: {
        Args: never
        Returns: {
          active_border: string
          avatar_bg: string
          avatar_url: string
          day_streak: number
          user_id: string
          username: string
          week_count: number
        }[]
      }
      user_achievements_stats: {
        Args: { p_user_id?: string }
        Returns: {
          chili_variety_count: number
          current_streak_days: number
          longest_streak_days: number
          total_plants: number
        }[]
      }
      user_daily_history: {
        Args: { p_days?: number; p_username: string }
        Returns: {
          date: string
          variety: number
        }[]
      }
      user_profile: {
        Args: { p_username: string }
        Returns: {
          active_border: string
          avatar_bg: string
          avatar_url: string
          longest_streak_days: number
          streak: number
          total_plants: number
          user_id: string
          username: string
          week_count: number
        }[]
      }
      user_weekly_history: {
        Args: { p_username: string; p_weeks?: number }
        Returns: {
          variety: number
          week_start: string
        }[]
      }
      weekly_history: {
        Args: { p_user_id?: string; p_weeks?: number }
        Returns: {
          hit_goal: boolean
          variety: number
          week_start: string
        }[]
      }
      weekly_variety: {
        Args: { p_user_id?: string; p_week_start?: string }
        Returns: number
      }
    }
    Enums: {
      article_type: "pillar" | "cluster"
      plant_category:
        | "fruit"
        | "vegetable"
        | "herb"
        | "nut_seed"
        | "legume"
        | "whole_grain"
        | "ferment"
      plant_color:
        | "red"
        | "orange"
        | "yellow"
        | "green"
        | "blue"
        | "purple"
        | "white"
        | "brown"
      submission_status: "pending" | "approved" | "rejected" | "duplicate"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      article_type: ["pillar", "cluster"],
      plant_category: [
        "fruit",
        "vegetable",
        "herb",
        "nut_seed",
        "legume",
        "whole_grain",
        "ferment",
      ],
      plant_color: [
        "red",
        "orange",
        "yellow",
        "green",
        "blue",
        "purple",
        "white",
        "brown",
      ],
      submission_status: ["pending", "approved", "rejected", "duplicate"],
    },
  },
} as const
