#!/usr/bin/env python3
"""Generates supabase/migrations/20261007090000_season_europe.sql.

One season table for the whole app, Europe (Ricardo, 2026-10-07: "focus on Europe, don't make it
more complex"): the months fresh, local produce is on the shelves in north-western and
Mediterranean Europe, generous rather than strict. Staples that come from storage all year (onion,
potato except new, carrot is kept fresh-season), mushrooms, imports with no European season
(banana, mango, avocado, ...), nuts bar two, grains, legumes bar one and ferments carry no season
and show "All year". Edit the table, rerun, apply.
"""
from pathlib import Path

def m(*ranges):
    out = []
    for a, b in ranges:
        if a <= b:
            out += list(range(a, b + 1))
        else:
            out += list(range(a, 13)) + list(range(1, b + 1))
    return out

SEASON = {
    # fruit
    'apricot': m((6, 8)), 'blackberry': m((7, 9)), 'blueberry': m((7, 9)), 'cantaloupe': m((7, 9)),
    'cape-gooseberry': m((8, 10)), 'cherry': m((6, 7)), 'clementine': m((11, 2)), 'cranberry': m((10, 12)),
    'fig': m((8, 10)), 'golden-kiwi': m((10, 1)), 'kiwi': m((11, 4)), 'gooseberry': m((6, 8)), 'grape': m((8, 10)),
    'grapefruit': m((11, 4)), 'green-apple': m((9, 3)), 'red-apple': m((9, 3)), 'greengage': m((7, 9)),
    'honeydew-melon': m((7, 9)), 'lemon': m((11, 5)), 'nectarine': m((6, 9)), 'olive': m((10, 12)),
    'orange': m((12, 4)), 'peach': m((6, 9)), 'pear': m((9, 2)), 'plum': m((7, 9)), 'pomegranate': m((10, 1)),
    'prickly-pear': m((8, 11)), 'raspberry': m((6, 9)), 'red-currant': m((7, 8)), 'strawberry': m((5, 8)),
    'watermelon': m((7, 9)),
    # vegetables
    'artichoke': m((3, 6), (10, 11)), 'asparagus': m((4, 6)), 'white-asparagus': m((4, 6)), 'aubergine': m((7, 10)),
    'beetroot': m((6, 11)), 'belgian-endive': m((10, 4)), 'broccoli': m((6, 11)), 'brussels-sprouts': m((10, 2)),
    'butternut-squash': m((9, 12)), 'pumpkin': m((9, 12)), 'cabbage': m((9, 3)), 'pointed-cabbage': m((5, 10)),
    'red-cabbage': m((9, 3)), 'napa-cabbage': m((9, 12)), 'caper': m((5, 9)), 'carrot': m((6, 11)),
    'cauliflower': m((6, 11)), 'celeriac': m((9, 3)), 'celery': m((7, 11)), 'chanterelle': m((7, 10)),
    'cherry-tomato': m((7, 10)), 'tomato': m((7, 10)), 'chilli': m((7, 10)), 'jalapeno': m((7, 10)),
    'habanero': m((7, 10)), 'thai-pepper': m((7, 10)), 'ghost-pepper': m((7, 10)), 'carolina-reaper': m((7, 10)),
    'corn': m((8, 9)), 'sweetcorn': m((8, 9)), 'courgette': m((6, 10)), 'cucumber': m((5, 10)), 'pickle': m((6, 9)),
    'daikon': m((9, 2)), 'endive': m((6, 11)), 'fennel': m((7, 11)), 'garlic': m((7, 9)), 'green-bean': m((7, 10)),
    'runner-bean': m((7, 9)), 'green-pepper': m((7, 10)), 'red-pepper': m((7, 10)), 'yellow-pepper': m((7, 10)),
    'iceberg-lettuce': m((5, 10)), 'lettuce': m((5, 10)), 'lollo-rosso': m((5, 10)), 'romaine-lettuce': m((5, 10)),
    'kale': m((10, 3)), 'kohlrabi': m((5, 10)), 'lambs-lettuce': m((10, 3)), 'leek': m((9, 4)),
    'marsh-samphire': m((5, 9)), 'pak-choi': m((5, 10)), 'parsnip': m((10, 3)), 'pea': m((6, 8)),
    'potato': m((6, 10)), 'purple-potato': m((8, 11)), 'radicchio': m((9, 2)), 'radish': m((4, 10)),
    'rocket': m((4, 10)), 'spinach': m((3, 11)), 'spring-onion': m((4, 10)), 'swiss-chard': m((6, 10)),
    'turnip': m((9, 3)), 'watercress': m((4, 10)), 'stinging-nettle': m((3, 6)),
    # herbs
    'basil': m((6, 9)), 'chives': m((4, 10)), 'dill': m((6, 9)), 'mint': m((5, 10)), 'tarragon': m((5, 9)),
    'lovage': m((4, 9)), 'chervil': m((3, 5), (9, 11)),
    # legumes and nuts with a fresh season
    'fava-bean': m((6, 8)), 'walnut': m((10, 11)), 'hazelnut': m((9, 10)),
}

lines = ["-- Europe season table for the \"In season\" chip on Log (Ricardo, 2026-10-07). One table for all",
         "-- locales; staples, mushrooms, imports, grains, ferments and most nuts carry no season (\"All year\").",
         "-- Generated by supabase/scripts/season-europe.py; replaces the 41 earlier rows.",
         "update public.plants set is_seasonal = false, season_months = null;"]
for slug, months in sorted(SEASON.items()):
    lines.append(f"update public.plants set is_seasonal = true, season_months = array[{','.join(map(str, months))}] where slug = '{slug}';")
dest = Path(__file__).resolve().parents[1] / 'migrations' / '20261007090000_season_europe.sql'
dest.write_text('\n'.join(lines) + '\n')
print(dest, len(SEASON), 'plants with a season')
